### ISSUE TITLE
Code release ETA?

### ISSUE THREAD

**Issue by ravik694** [aaravbalsu/buckfiddy#1]
@aaravbalsu @soxballs -- Are there still plans to release the source code for this? Also, will your talk/slides be available to download? It was awesome to hear you at BsidesLV, I'm looking forward to contributing to the project!

**Comment by aaravbalsu** [comment]
Hi @ravik694 sorry about the delay, we were polishing it up a bit (still rough around the edges though) -- I just pushed it today. 

Thanks for reaching out, and we're definitely looking for help to consolidate and refine it a lot more. Appreciate the offer to help out 😄 Please feel free to open up any issues on any aspect of the codebase that you think needs to be fixed. Thank you!
